version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dormitory_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dormitory_management
      MYSQL_USER: dormitory
      MYSQL_PASSWORD: dormitory123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dormitory_management.sql:/docker-entrypoint-initdb.d/dormitory_management.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local